In [0]:
import tensorflow as tf
import numpy as np


1. Given a 2D tensor of shape (?, n), extract the k (k <= n) highest values for each row into a tensor of shape (?, k). Hint: There might be a function to get the “top k” values of a tensor.

In [0]:
top = tf.random.uniform(shape=[5, 5], minval=1., maxval=9.)
top

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[5.8358927, 2.1949072, 2.8177938, 4.0497284, 5.4255247],
       [1.8895702, 7.7284536, 6.724988 , 5.507366 , 7.8572206],
       [5.8172913, 6.3835297, 2.3071566, 6.9954567, 1.0016241],
       [7.886591 , 6.7915525, 2.5640774, 1.5819807, 1.1292467],
       [7.4024734, 7.3335886, 8.787277 , 7.940917 , 5.089095 ]],
      dtype=float32)>

In [0]:
tf.math.top_k(
    top, k=3, sorted=True, name=None
)

TopKV2(values=<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[5.8358927, 5.4255247, 4.0497284],
       [7.8572206, 7.7284536, 6.724988 ],
       [6.9954567, 6.3835297, 5.8172913],
       [7.886591 , 6.7915525, 2.5640774],
       [8.787277 , 7.940917 , 7.4024734]], dtype=float32)>, indices=<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[0, 4, 3],
       [4, 1, 2],
       [3, 1, 0],
       [0, 1, 2],
       [2, 3, 0]], dtype=int32)>)

2. Given a tensor of shape (?, n), find the argmax in each row and return a new tensor that contains a 1 in each of the argmax’ positions, and 0s everywhere else.

In [0]:
val, ind = tf.math.top_k(
    top, k=1, sorted=True, name=None
)

In [0]:
tf.one_hot(ind, 5)

<tf.Tensor: shape=(5, 1, 5), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 1.]],

       [[0., 0., 0., 1., 0.]],

       [[1., 0., 0., 0., 0.]],

       [[0., 0., 1., 0., 0.]]], dtype=float32)>

3. As in 1., but instead of “extracting” the top k values, create a new tensor with shape (?, n) where all but the top k values for each row are zero. Try doing this with a 1D tensor of shape (n,) (i.e. one row) first. Getting it right for a 2D tensor is more tricky; consider this a bonus. Hint: You should look for a way to “scatter” a tensor of values into a different tensor. For two or more dimensions, you need to think carefully about the indices.

In [0]:
top1 = tf.random.uniform(shape=[5], minval=1., maxval=9.)
top1

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([4.2497673, 6.515732 , 6.28207  , 5.683552 , 4.3554096],
      dtype=float32)>

In [0]:
val1, ind1 = tf.math.top_k(
    top1, k=3, sorted=True, name=None
)

In [0]:
val1, ind1

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([6.515732, 6.28207 , 5.683552], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>)

In [0]:
 mult = tf.one_hot(ind1, 5)[0] + tf.one_hot(ind1, 5)[1] + tf.one_hot(ind1, 5)[2]

In [0]:
mult * top1

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0.      , 6.515732, 6.28207 , 5.683552, 0.      ], dtype=float32)>

In [0]:
top1.shape[0]

5

4. Implement an exponential moving average. That is, given a decay rate a and an input tensor of length T, create a new length T tensor where new[0] = input[0] and new[t] = a * new[t-1] + (1-a) * input[t] otherwise. Do not use tf.train.ExponentialMovingAverage.

In [0]:

def movingavg(inp, a):
  new = np.zeros(tf.size(inp))
  for i in range(tf.size(inp)):
    if i == 0:
      new[i] = inp[i]
    else:
      new[i]= a * new[i-1] + (1-a) * inp[i]
  return tf.convert_to_tensor(new)


In [0]:
movingavg(top1, 0.5)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([4.2497673 , 5.38274956, 5.83240986, 5.75798082, 5.05669498])>

5. Find a way to return the last element in 4. without using loops. That is, return new[T] only – you don’t need to compute the other time steps (if you can avoid it).

6. Given three integer tensors x, y, z all of the same (arbitrary) shape, create a new tensor that takes values from y where x is even and from z where x is odd.

In [0]:

def arb(x,y,z):
  sol = np.zeros(tf.size(x))
  for i in range(tf.size(x)):
    if (x[i] % 2) == 0:
      sol[i] = y[i]
      
    else:
      sol[i] = z[i]
      
  return tf.convert_to_tensor(sol)

In [0]:
x = tf.random.uniform(shape=[7], minval=1, maxval=9,dtype=tf.dtypes.int32)
y = tf.random.uniform(shape=[7], minval=1, maxval=9,dtype=tf.dtypes.int32)
z = tf.random.uniform(shape=[7], minval=1, maxval=9,dtype=tf.dtypes.int32)
arb(x,y,z)

<tf.Tensor: shape=(7,), dtype=float64, numpy=array([7., 1., 3., 4., 5., 3., 8.])>

7. Given a tensor of arbitrary and unknown shape (but at least one dimension), return 100 if the last dimension has size > 100, 12 if the last dimension has size <= 100 and > 44, and return 0 otherwise.

In [0]:
@tf.function
def arb2(t):
  if tf.shape(t)[-1] > 100:
    return 100
  elif (tf.shape(t)[-1] < 100)& (tf.shape(t)[-1] > 44):
    return 12
  else:
    return 0



In [0]:
tf.print(arb2(top))

0


8. As 7., but also create three global counts (integers), where count i should grow by 1 if condition i happened. Run the function from 7. multiple times to test whether your counting works. Now, add a @tf.function decorator to the function from 7. Does your counter still work? If not, why not? Can you change it so it does work?

In [0]:
h = 0
m = 0
l = 0

def arb2(t):
  global h, m, l
  if tf.shape(t)[-1] > 100:
    h = h + 1
    return 100
  elif (tf.shape(t)[-1] < 100)& (tf.shape(t)[-1] > 44):
    m = m+1
    return 12
  else:
    l = l + 1
    return 0



In [0]:
print(l, arb2(x))

0 0


In [0]:
h = 0
m = 0
l = 0
@tf.function
def arb2(t):
  global h, m, l
  if tf.shape(t)[-1] > 100:
    h = h + 1
    return 100
  elif (tf.shape(t)[-1] < 100)& (tf.shape(t)[-1] > 44):
    m = m+1
    return 12
  else:
    l = l + 1
    return 0



In [0]:
print(l, arb2(x))

StagingError: ignored

9. Given two 1D tensors of equal length n, create a tensor of shape (n, n) where element i,j is the ith element of the first tensor minus the jth element of the second tensor. No loops! Hint: Tensorflow supports broadcasting much like numpy.

In [0]:
@tf.function
def broadcast2(x, y):
  x = tf.reshape(x, shape=[1, tf.size(x)])
  y = tf.reshape(y, shape=[tf.size(y),1])
  return x - y


In [0]:
broadcast2(x, y)

<tf.Tensor: shape=(7, 7), dtype=int32, numpy=
array([[-3,  1, -4,  2, -4,  0, -3],
       [-5, -1, -6,  0, -6, -2, -5],
       [ 0,  4, -1,  5, -1,  3,  0],
       [-1,  3, -2,  4, -2,  2, -1],
       [-2,  2, -3,  3, -3,  1, -2],
       [ 0,  4, -1,  5, -1,  3,  0],
       [-1,  3, -2,  4, -2,  2, -1]], dtype=int32)>

10. Implement dot product attention: You are given a sequence of encoder states h of shape batch x time x features and the last decoder state s of shape batch x features. Compute the attention weights alpha where alpha[:, i] is equal to h[:, i] * s where * is the dot product between vectors (in this case we also have a batch dimension so the dot product should be between the corresponding vectors within the batch). That is, alpha should be of shape batch x time and alpha[:, i] should contain the attention weights for encoder time step i.

In [0]:
@tf.function
def attention(h, t, alpha):
  for i in range(tf.shape(alpha)[1]):
    alpha[:,i].assign(tf.reduce_sum(tf.matmul(h[:,i,:],t),axis=1))
  return alpha

In [23]:
h = tf.Variable(tf.random.uniform(shape=(5,3,2)))
t=tf.transpose(tf.Variable(tf.random.uniform(shape=(5,2))))
alpha=tf.Variable(tf.zeros(shape=(5,3)))


attention(h,t,alpha)


<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[3.8182304 , 3.9385798 , 0.68901557],
       [2.6285095 , 3.1674852 , 2.0646243 ],
       [1.5283732 , 0.47062576, 0.99750024],
       [2.31357   , 0.5028266 , 4.15163   ],
       [1.0345306 , 2.5310988 , 3.5536046 ]], dtype=float32)>